server:
  port: 8091
spring:
  # 开发环境数据源配置
  datasource:
    url: jdbc:mysql://139.159.236.186:6606/2code?pinGlobalTxToPhysicalConnection=true&autoReconnect=true&useUnicode=true&serverTimezone=GMT%2b8&useSSL=false&characterEncoding=utf-8
    username: root
    password: MySql@#$123
# mybatis-plus 配置
mybatis-plus:
  configuration:
    # 开发环境, 打印 sql 到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
debug: false
