spring:
  application:
    name: 2code
  main:
    allow-bean-definition-overriding: true
  # 数据源默认配置
  datasource:
    hikari:
      # 最小连接数
      minimum-idle: 3
      # 最大连接数
      maximum-pool-size: 20
      # 允许闲置的最长时间 ms
      idle-timeout: 30000
      # 池中连接最长生命周期
      max-lifetime: 180000
  # jackson 解析 json 配置
  jackson:
    # 为 null 的属性不转换
    default-property-inclusion: non_null
    # 驼峰与下划线互转
    property-naming-strategy: SNAKE_CASE
    # 默认日期格式
    date-format: yyyy-MM-dd HH:mm:ss
  # 环境配置, 默认为开发环境
  profiles:
    # 从
    active: @profiles.active@
  # spring security 配置
  security:
    user:
      name: admin
      password: Admin123456@qq.com
  freemarker:
    suffix: .html
    request-context-attribute: request
mybatis-plus:
  global-config:
    db-config:
      # id 类型, 唯一 id
      id-type: auto
      table-prefix: 2code
  configuration:
    # 实体类与数据库字段映射：驼峰与下划线互相转换, 满足规则的字段不需要 @TableFiled 注明数据库字段
    map-underscore-to-camel-case: true
    # mapper 方法参数不需要用 @Param 注明参数名
    use-actual-param-name: true
    # 禁用缓存
    cache-enabled: false