<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>欢迎光临</title>
</head>
<body>
<div class="flex" style="position: fixed;top: 0;bottom: 0;left: 0;right: 0; background: #fff;">
    <div class="img" style='width: 66%;margin:33vh auto'>
        <img src="/images/loading.gif" alt="" style="width: 100%">
    </div>
</div>
<script type="text/javascript">
    // 打开对应网址
    alert("jump")
    setTimeout(() => {
        location.assign('//');
    }, 1000)
</script>
</body>
</html>